### ISSUE TITLE
user name & velog name 차이점

### ISSUE THREAD

**Issue by coolchaem** [youngjewoo/blog_server#7]
DB 안에 user name과 velog name이 따로 있는데, PostAPI에서 velog name으로 user name쓰고 있잖아요.
user name 용도가 부정확합니다.

![image](https://user-images.githubusercontent.com/20571183/146715795-4c942ac8-6db9-4daf-8c67-f8f33e503d7a.png)

Q. 저희 velog name db field를 user name field로 변경해야 할까요?
- 아니면, 반영하지 않은 변경한 브랜치를 가지고 있나요?

Q. 아니면 구분해서 사용하는 기능을 알고 있나요?

**Comment by yeojini** [comment]
저도 이게 헷갈립니닷 ㅜㅜ

**Comment by youngjewoo** [comment]
흠.. 저도 user_name을 사용하는 부분을 못 보기는 했는데 ㅠ
velog_name을 제거하고 user_name으로만 사용하는 편이 덜 헷갈릴까요??

**Comment by coolchaem** [comment]
> 흠.. 저도 user_name을 사용하는 부분을 못 보기는 했는데 ㅠ velog_name을 제거하고 user_name으로만 사용하는 편이 덜 헷갈릴까요??

저 케이스 찾았어여
user name이 진짜 있긴하네용

![image](https://user-images.githubusercontent.com/20571183/146764196-09467bd2-546c-4397-b67d-163b7b3d8a0c.png)

![image](https://user-images.githubusercontent.com/20571183/146764206-52e3a55e-9ecc-4acc-96e4-173a03b42a79.png)

**Comment by coolchaem** [comment]
User type의 id가 velog name으로 사용되어야 할 거 같네요
username은 유지시키고

**Comment by youngjewoo** [comment]
아 생각해보니 저 페이지 보고 username 추가했었지..; 죄송함다;; 제가 해놓고...

근데 "User type의 id가 velog name으로 사용되어야 할 거 같네요" 이 부분이 살짝 이해 안 갑니다 ㅠ
Client 쪽 코드 말씀하시는 건가요?? @coolchaem

**Comment by coolchaem** [comment]
> 아 생각해보니 저 페이지 보고 username 추가했었지..; 죄송함다;; 제가 해놓고...
> 
> 근데 "User type의 id가 velog name으로 사용되어야 할 거 같네요" 이 부분이 살짝 이해 안 갑니다 ㅠ Client 쪽 코드 말씀하시는 건가요?? @coolchaem

넵 클라이언트에서 user type에 있는 id가 velog name으로 보이는데
db에선 id가 number type의 unique index죠?
두가지에 대해서 맞추는게 좋을지 의견주세요!
저는 통일하는게 좋을 거 같다고 생각해서요

**Comment by youngjewoo** [comment]
넹 DB에서는 id가 number type의 id 입니당.

`DB table에서 number 타입의 user_id를 제거하고 유저 판별을 velog_name으로만 하는 것이 좋을 거 같다`

라는 의견이실까요??

**Comment by coolchaem** [comment]
'DB table에서 number 타입의 user_id를 제거하고 유저 판별을 velog_name으로만 하는 것이 좋을 거 같다'

네! 이렇게하면 문제가 있을까요!?

**Comment by youngjewoo** [comment]
보통 id 컬럼 정도는 하나 있는게 관습적으로 익숙하기는 한데 빼도 지금 당장 문제될 것은 없어 보입니다.
@yeojini 어떻게 생각하시나요??
